name: push-to-main

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v1

    - name: Install Docker using Docker's official script
      run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: start docker compose
      run: docker-compose up -d --build

    - name: install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.4'

    - name: build virtual env
      run: python -m venv gh_actions && source ./gh_actions/bin/activate && pip3 install -r requirements.txt

    - name: seed s3 data
      run: ./gh_actions/bin/python init_data.py

    - name: extract data using pyspark
      run: ./gh_actions/bin/python extract.py